text='Не знаю, как там в Лондоне, я не была. Может, там собака — друг человека. А у нас управдом — друг человека!'
print('Шаг1 - Количество символов - ', len(text))
print('Шаг2 - Развёрнутая строка - ',text[::-1])
print('Шаг3 - Каждое слово с большой буквы - ',text.title())
print('Шаг4 - Весь текст прописныам буквами - ',text.upper())
print("Шаг5а - Количество вхождений 'нд' - ",text.count('нд'))
print("Шаг5б - Количество вхождений 'ам' - ",text.count('ам'))
print("Шаг5в - Количество вхождений 'о' - ",text.count('о'))
split = text.split('. ')
print('Шаг6а - Перенос - ','\n'.join(split))
print('Шаг6б - Замена слова - ',text.replace('управдом', '"ПРЕЗИДЕНТ"'))
print('Шаг6в - Замена заглавных букв прописными и наоборот - ',text.swapcase())
print('Шаг6г - Умножение - ',text*2)
print('Шаг6д - Вывод интервала строки - ',text[5:80])
def conversely(text):
    text = text.split()
    text.reverse()
    text2 = ' ' .join(text)
    return text2
string = conversely(text)
print('Шаг7 - Обратный порядок слов - ',string)
print('Шаг8 - Вывод исходной строки - ',text)